name: zawiyah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  http: ^1.2.1
  provider: ^6.1.0
  just_audio: ^0.9.34
  flutter_downloader: ^1.11.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  translator: ^1.0.0
  # Corrected Firebase versions
  # core 2 32 0
  # auth 4 10 0
  firebase_core: ^2.32.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.6.5
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  screen_brightness: ^0.2.1
  intl: ^0.18.1
  geolocator: ^10.1.0
  flutter_compass: ^0.8.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/flags/
    - assets/mushaf/
    - assets/99namesofAllah/
    - assets/manzil/
